// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using call_replay.Models;

#nullable disable

namespace call_replay.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("call_replay.Models.WishLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AudioFileUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonWishing")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("WishAudio")
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("WishLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
